// Canonical Internal Statuses

export const TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
};

export const PURCHASE_STATUS = {
  PENDING: 'PENDING',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURNED: 'RETURNED',
  REFUNDED: 'REFUNDED',
  UNKNOWN: 'UNKNOWN',
} as const;
